include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - "build/**" # iOS ビルドが SourcePackages にチェックアウトするプラグインのソースを解析対象から除外
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - android/**
    - ios/**
    - web/**
