name: banana
description: Flutter入門
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.2"

dependencies:
  google_generative_ai: ^0.4.7
  file_picker: ^12.2.0
  arkit_plugin: ^1.5.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^4.0.7
  google_fonts: ^8.2.1
  flutter_slidable: ^4.0.3
  json_annotation: ^4.12.0
  freezed_annotation: ^3.1.0
  liveroom: ^1.3.0
  percent_indicator: ^4.2.5
  go_router: ^18.0.1
  pixel_color_image: ^1.6.0
  web_socket_channel: ^3.0.3
  firebase_core: ^4.14.0
  firebase_analytics: ^12.5.0
  firebase_auth: ^6.6.1
  google_sign_in: ^7.2.0
  device_preview_minus: ^1.6.0 # device_preview が開発停止したため代わりに使う
  envied: ^1.3.8
  shared_preferences: ^2.5.5
  cloud_firestore: ^6.9.0
  intl: ^0.20.3
  youtube_player_iframe: ^6.0.2
  url_launcher: ^6.3.2
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  freezed: ^4.0.1
  build_runner: ^2.16.1
  json_serializable: ^6.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.9
  envied_generator: ^1.3.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/google_fonts/
    - assets/fonts/
    - assets/stub/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Medium.ttf
