// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBN8jjJCdEKJVqyCoJywcGtFI-j48SICE',
    appId: '1:940366600997:web:eb3cc514198f5fa301d8cc',
    messagingSenderId: '940366600997',
    projectId: 'rubydog-banana',
    authDomain: 'rubydog-banana.firebaseapp.com',
    storageBucket: 'rubydog-banana.appspot.com',
    measurementId: 'G-4FRS61GX6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAWl9SdJ0fTA1avoiGlN1ErC_Axk6JZ88',
    appId: '1:940366600997:android:3324c1d7e6d7d14b01d8cc',
    messagingSenderId: '940366600997',
    projectId: 'rubydog-banana',
    storageBucket: 'rubydog-banana.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLIq4HxWvBcaYTqHh0yhSP8OKG6R-nkyg',
    appId: '1:940366600997:ios:a5629d66f19aeb1301d8cc',
    messagingSenderId: '940366600997',
    projectId: 'rubydog-banana',
    storageBucket: 'rubydog-banana.appspot.com',
    iosClientId: '940366600997-tenqpkuv2s1u0mklc1uk0ad3mvms61bn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSample',
  );
}
