import 'package:banana/hello_rubydog/video.dart';
import 'package:banana/clash/main.dart' as clash;
import 'package:banana/hooks/main.dart' as hooks;
import 'package:banana/nintendo/home.dart' as nintendo;
import 'package:banana/hello_rubydog/special_examples.dart';

final specialVideos = [
  Video(
    'リバーポッド 01',
    'special-riverpod01.png',
    ['ConsumerWidget', 'HookConsumerWidget他'],
    ['riverpod', 'riverpod_hooks他'],
    () => const Riverpod01Page(),
    'https://github.com/rbdog/flutter_note/tree/main/lib/riverpod#%E6%A1%88%E5%86%85%E6%89%80',
    '0HVru4WtdWo',
  ),
  Video(
    'リバーポッド 02',
    'special-riverpod02.png',
    [],
    ['riverpod_generator', 'Provider', 'AsyncNotifier他'],
    () => const NoExamplePage(),
    'https://github.com/rbdog/flutter_note/tree/main/lib/riverpod#%E6%A1%88%E5%86%85%E6%89%80',
    'OLYcFlPp_rM',
  ),
  Video(
    'リバーポッド 03',
    'special-riverpod03.png',
    [],
    ['watch', 'read', 'listen', 'AsyncValue他'],
    () => const Riverpod03Page(),
    'https://github.com/rbdog/flutter_note/tree/main/lib/riverpod#%E6%A1%88%E5%86%85%E6%89%80',
    'vuT2kbh0ihA',
  ),
  Video(
    'リバーポッド 04',
    'special-riverpod04.png',
    [],
    ['keepAlive', 'ProviderFamily', 'overrideWith他'],
    () => const Riverpod04Page(),
    'https://github.com/rbdog/flutter_note/tree/main/lib/riverpod#%E6%A1%88%E5%86%85%E6%89%80',
    'hMDs2QAIDDg',
  ),
  Video(
    'フック入門',
    'special-hooks.png',
    ['HookWidget'],
    ['useState', 'useEffect', 'カスタムHook他'],
    () => const hooks.MyApp(),
    'https://github.com/rbdog/flutter_note/tree/main/lib/hooks',
    'Mbz6tGXYYL4',
  ),
  Video(
    'VSCode 便利機能集',
    'special-vscode.png',
    [],
    ['スニペット', 'ショートカット', '拡張機能他'],
    () => const hooks.MyApp(),
    'https://github.com/rbdog/flutter_note/tree/main/lib/vscode',
    'hQwQkOav7Sk',
  ),
  Video(
    'フォルダ構成',
    'special-folders.png',
    [],
    ['アーキテクチャ', 'レイヤー他'],
    () => const hooks.MyApp(),
    'https://github.com/rbdog/flutter_note_folders/tree/main/lib',
    'UMpInO2giz4',
  ),
  Video(
    '状態管理とは？',
    'special-state-management.png',
    [],
    ['状態管理', '宣言型', 'Redux', 'プロバイダー他'],
    () => const NoExamplePage(),
    null,
    'FjH-_cESE7Q',
  ),
  Video(
    '非同期コードの書き方',
    'special-async-await.png',
    [],
    ['async', 'await', 'Future'],
    () => const NoExamplePage(),
    'https://github.com/rbdog/flutter_note/tree/main/lib/async_await',
    '2e4zM-2EUEs',
  ),
  Video(
    'アプリ同士で通信',
    'special-websocket.png',
    [],
    ['WebSocket', 'HTTP', 'ハンドシェイク'],
    () => const WebsocketPage(),
    'https://github.com/rbdog/flutter_note/tree/main/lib/liveroom',
    'U4n2YTrcVbA',
  ),
  Video(
    '画像のピクセル色を取得',
    'special-pixel-color.png',
    [],
    ['pixel_color_image'],
    () => const PixelColorPage(),
    'https://github.com/rbdog/flutter_note/tree/main/lib/pixel_color_image',
    'Fh8-xkFxocs',
  ),
  Video(
    '質問コーナー 01',
    'special-qa01.png',
    [],
    ['Push&Pop', 'コントローラー', 'コンテキスト'],
    () => const NoExamplePage(),
    'https://github.com/rbdog/flutter_note/tree/main/lib/qa/01',
    'l1sUCFtcsjo',
  ),
  Video(
    'ARの将来と開発知識',
    'special-ar.png',
    ['ARKitSceneView'],
    ['AR', 'Vision Pro', 'ARCore'],
    () => const NoExamplePage(),
    'https://github.com/rbdog/flutter_note/tree/main/lib/ar',
    'JFG6GPb_byE',
  ),
  Video(
    '第一回 有名アプリをクローン',
    'special-nintendo.png',
    [],
    ['Myニンテンドー', 'クローン'],
    () => const nintendo.Home(),
    'https://github.com/rbdog/flutter_note/tree/main/lib/nintendo',
    'AYZBtz7pK-E',
  ),
  Video(
    '第二回 有名アプリをクローン',
    'special-clash.png',
    [],
    ['Clash Royale', 'ゲームUI', 'PageController'],
    () => const clash.HomePage(),
    'https://github.com/rbdog/flutter_note/tree/main/lib/clash',
    'R_lhSBsLMFs',
  ),
];
